// src/content/mobs.js
// @ts-check
/** @type {Record<string, any>} */
export const MOB_TEMPLATES = {
  "dummy": {
    id: "dummy", name: "Training Dummy",
    baseStats: {
      str: 5,
      dex: 5,
      int: 5,
      vit: 8,
      con: 8,
      will: 5,
      luck: 5,
      maxHP: 35,
      maxStamina: 10,
      maxMana: 0,
      baseSpeed: 1.0,
    },
    equipment: {},
    actions: ["strike"],
    tags: ["construct", "training", "stationary"],
  },
  "brigand": {
    id: "brigand", name: "Brigand",
    baseStats: {
      str: 9,
      dex: 9,
      int: 6,
      vit: 9,
      con: 9,
      will: 6,
      luck: 8,
      maxHP: 24,
      maxStamina: 12,
      maxMana: 0,
      baseSpeed: 1.0,
    },
    loadout: ["short_sword"], // resolved by factory
    actions: ["strike", "move_towards_target"],
    tags: ["humanoid", "bandit", "melee"],
  },
  "pyromancer": {
    id: "pyromancer", name: "Pyromancer",
    baseStats: {
      str: 5,
      dex: 7,
      int: 12,
      vit: 8,
      con: 7,
      will: 12,
      luck: 6,
      maxHP: 20,
      maxStamina: 8,
      maxMana: 16,
      baseSpeed: 1.0,
    },
    loadout: ["flame_sword", "cloak_cold"],
    innate: { affinities: { fire: 0.10 } },
    actions: ["fire_bolt", "strike"],
    tags: ["humanoid", "caster", "fire"],
  },
  "skeleton_warrior": {
    id: "skeleton_warrior", name: "Skeleton Warrior",
    baseStats: {
      str: 10,
      dex: 8,
      int: 4,
      vit: 9,
      con: 9,
      will: 7,
      luck: 4,
      maxHP: 28,
      maxStamina: 10,
      maxMana: 0,
      baseSpeed: 0.9,
    },
    loadout: ["long_sword"],
    innate: { resists: { poison: 0.25 } },
    actions: ["strike", "move_towards_target"],
    tags: ["undead", "melee", "guardian"],
  },
};
