// src/config.js
// Central configuration for tweakable gameplay and UI values.
import {
  DEFAULT_STATUS_DURATION_TURNS,
  DEFAULT_STATUS_STACKS,
  BURN_MAX_STACKS,
  BURN_TICK_DAMAGE_PER_STACK,
} from "../constants.js";

export const COMBAT_ATTACK_TYPE_HINT_DURATION_MS = 250;

export const EVENT_LOG_RING_MAX = 200;
export const EVENT_LOG_LATEST_DEFAULT = 50;

export const DEBUG_OVERLAY_LOG_LIMIT = 60;
export const DEBUG_OVERLAY_BREAKDOWN_LIMIT = 8;
export const DEBUG_OVERLAY_MIN_PERCENT_DISPLAY = 1e-4;
export const DEBUG_OVERLAY_NUMBER_DIGITS = 2;

export const DEV_CONSOLE_DEFAULT_STATUS_DURATION = DEFAULT_STATUS_DURATION_TURNS;
export const DEV_CONSOLE_DEFAULT_STATUS_STACKS = DEFAULT_STATUS_STACKS;
export const DEV_CONSOLE_DEFAULT_SIM_ITERATIONS = 40;
export const DEV_CONSOLE_RAF_FALLBACK_DELAY_MS = 16;
export const DEV_CONSOLE_LOOT_TOAST_TRANSITION_MS = 150;
export const DEV_CONSOLE_LOOT_TOAST_VISIBLE_DURATION_MS = 2600;
export const DEV_CONSOLE_LOOT_TOAST_HIDE_DELAY_MS = 200;
export const DEV_CONSOLE_LOOT_TOAST_TRANSLATE_Y_PX = 8;
export const DEV_CONSOLE_LOOT_TOAST_CONTAINER_RIGHT_PX = 16;
export const DEV_CONSOLE_LOOT_TOAST_CONTAINER_BOTTOM_PX = 96;
export const DEV_CONSOLE_LOOT_TOAST_CONTAINER_GAP_PX = 8;
export const DEV_CONSOLE_LOOT_TOAST_CONTAINER_Z_INDEX = 2000;
export const DEV_CONSOLE_LOOT_TOAST_PADDING = "8px 12px";
export const DEV_CONSOLE_LOOT_TOAST_BORDER_RADIUS_PX = 8;
export const DEV_CONSOLE_LOOT_TOAST_FONT_SIZE_PX = 12;
export const DEV_CONSOLE_LOOT_TOAST_BOX_SHADOW = "0 8px 24px rgba(15,23,42,0.35)";

// Combat status tuning
export const STATUS_BURN_MAX_STACKS = BURN_MAX_STACKS;
export const STATUS_BURN_BASE_DAMAGE = BURN_TICK_DAMAGE_PER_STACK;
export const STATUS_SLOWED_ACTION_SPEED_PENALTY_PER_STACK = 0.1;
export const STATUS_SLOWED_MOVE_AP_DELTA = 0.1;
export const STATUS_STUNNED_ACTION_SPEED_PENALTY_PER_STACK = 1.0;
export const STATUS_HASTE_ACTION_SPEED_BONUS_PER_STACK = 0.15;

